In [2]:
from sklearn.preprocessing import OneHotEncoder

import numpy as np 

In [4]:
words = [["I"], ["love"], ["NLP"]]

# Initialize encoder
encoder = OneHotEncoder(sparse_output=False)

# Fit and transform
one_hot = encoder.fit_transform(words)

# Show result
print("Vocabulary:", encoder.categories_)
print("One-hot encoded:\n", one_hot)

Vocabulary: [array(['I', 'NLP', 'love'], dtype=object)]
One-hot encoded:
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
